export const infinixStoryPage = {
  label: "Infinix × Bawany",
  brand: {
    eyebrow: "The Brand",
    headline: "Infinix — built for the next generation.",
    body: [
      "Infinix is a global smartphone brand known for bold design, long battery life, and flagship features at accessible prices. Since 2015, Bawany Enterprises has been Pakistan's first official distributor — bringing every device through legal channels, fully PTA approved.",
      "Not a reseller. Not a middleman. The original partner — still standing behind authentic supply, warranty, and after-sales support across the country.",
    ],
    points: [
      { label: "Since", value: "2015" },
      { label: "Status", value: "1st Official Distributor" },
      { label: "Devices", value: "100% PTA Approved" },
    ],
  },
  productsLabel: "Products",
  productsHeadline: "Explore the Infinix lineup.",
  seriesTabs: [
    { id: "latest", label: "Latest Product" },
    { id: "gt", label: "GT Series" },
    { id: "note", label: "NOTE Series" },
    { id: "hot", label: "HOT Series" },
    { id: "smart", label: "SMART Series" },
    { id: "zero", label: "ZERO Series" },
  ],
  products: [
    {
      id: "gt-20-pro",
      series: "gt",
      name: "GT 20 Pro",
      image: "/assets/infinix/series/gt-20-pro.jpg",
      latest: true,
    },
    {
      id: "gt-10-pro",
      series: "gt",
      name: "GT 10 Pro",
      image: "/assets/infinix/series/gt-10.jpg",
      latest: true,
    },
    {
      id: "note-40-pro",
      series: "note",
      name: "NOTE 40 Pro",
      image: "/assets/infinix/series/note-40-pro.jpg",
      latest: true,
    },
    {
      id: "note-40-5g",
      series: "note",
      name: "NOTE 40 5G",
      image: "/assets/infinix/series/note-40-5g.jpg",
      latest: true,
    },
    {
      id: "note-40",
      series: "note",
      name: "NOTE 40",
      image: "/assets/infinix/series/note-40.jpg",
      latest: false,
    },
    {
      id: "note-30-pro",
      series: "note",
      name: "NOTE 30 Pro",
      image: "/assets/infinix/series/note-30-pro.jpg",
      latest: false,
    },
    {
      id: "note-12-pro",
      series: "note",
      name: "NOTE 12 Pro 5G",
      image: "/assets/infinix/series/note-12.jpg",
      latest: false,
    },
    {
      id: "hot-40",
      series: "hot",
      name: "HOT 40",
      image: "/assets/infinix/series/hot-40.jpg",
      latest: true,
    },
    {
      id: "hot-40i",
      series: "hot",
      name: "HOT 40i",
      image: "/assets/infinix/series/hot-40i.jpg",
      latest: false,
    },
    {
      id: "hot-30",
      series: "hot",
      name: "HOT 30",
      image: "/assets/infinix/series/hot-30.jpg",
      latest: false,
    },
    {
      id: "smart-8-pro",
      series: "smart",
      name: "SMART 8 Pro",
      image: "/assets/infinix/series/smart-8-pro.jpg",
      latest: true,
    },
    {
      id: "smart-8",
      series: "smart",
      name: "SMART 8",
      image: "/assets/infinix/series/smart-8.jpg",
      latest: false,
    },
    {
      id: "smart-7",
      series: "smart",
      name: "SMART 7",
      image: "/assets/infinix/series/smart-7.jpg",
      latest: false,
    },
    {
      id: "zero-30",
      series: "zero",
      name: "ZERO 30",
      image: "/assets/infinix/series/zero-30.jpg",
      latest: true,
    },
    {
      id: "zero-ultra",
      series: "zero",
      name: "ZERO Ultra",
      image: "/assets/infinix/series/zero.jpg",
      latest: false,
    },
    {
      id: "zero-8",
      series: "zero",
      name: "ZERO 8",
      image: "/assets/infinix/series/zero2.jpg",
      latest: false,
    },
  ],
  viewAllHref: "https://www.infinixmobility.com/",
  cta: {
    headline: "Ready to stock Infinix?",
    body: "Dealers and retailers across Pakistan trust Bawany for authentic Infinix smartphones across GT, NOTE, HOT, SMART, and ZERO.",
    button: "Become a Partner",
  },
} as const;
